version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: mongo:5.0.6
    environment:
      - MONGO_INITDB_DATABASE=iqAir
    ports:
      - 27019:27017
    volumes:
      - mongodb_data_container:/data/db
      
volumes:
  mongodb_data_container: